const constants ={

    REQUEST_ADD_TODO:'REQUEST_ADD_TODO',
    SUCCESS_ADD_TODO:'SUCCESS_ADD_TODO',
    ERROR_ADD_TODO:'ERROR_ADD_TODO',

    REQUEST_GET_TODO:'REQUEST_GET_TODO',
    SUCCESS_GET_TODO:'SUCCESS_GET_TODO',
    ERROR_GET_TODO:'ERROR_GET_TODO',

    REQUEST_EDIT_TODO:'REQUEST_EDIT_TODO',
    SUCCESS_EDIT_TODO:'SUCCESS_EDIT_TODO',
    ERROR_EDIT_TODO:'ERROR_EDIT_TODO',

    REQUEST_TOGGLE_TODO:'REQUEST_TOGGLE_TODO',
    SUCCESS_TOGGLE_TODO:'SUCCESS_TOGGLE_TODO',
    ERROR_TOGGLE_TODO:'ERROR_TOGGLE_TODO',    
}
export default constants;